version: '2'
services:
    jhipstersampleapplicationmicroservicegateway-app:
        image: jhipstersampleapplicationmicroservicegateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersampleapplicationmicroservicegateway-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleApplicationMicroServiceGateway
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplicationmicroservicegateway-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersampleapplicationmicroservicegateway-mongodb
